
import { NextApiRequest, NextApiResponse } from 'next';

const posts = [
  {
    id: 1,
    slug: "la-casa-blanca",
    title: "La casa blanca de color verde",
    content: { "blocks": [{ "key": "6sv9n", "text": "La casa blanca de color verde", "type": "header-one", "depth": 0, "inlineStyleRanges": [{ "offset": 0, "length": 22, "style": "BOLD" }], "entityRanges": [], "data": {} }, { "key": "q1nn", "text": "El dia de hoy se va celebrar una nueva version de la aplicacion de la Unidad Educativa Cardenal Gonzalez Zumarraga, este dia es un dia especial que todos compartimos y añoramos demasiado.Para conocer mas acerca de en que consiste esta celebracion dirigite a la siguiente publicacion, click aquí.Un dia como hoy 8 de Agosto del 2020, se conmemora la independencia de la unidad educativa Cardenal Gonzalez Zumarraga. Según cita el obispo Carlos Fred.", "type": "unstyled", "depth": 0, "inlineStyleRanges": [{ "offset": 290, "length": 4, "style": "UNDERLINE" }], "entityRanges": [{ "offset": 290, "length": 4, "key": 0 }], "data": {} }, { "key": "fsc9b", "text": "En este dia conmemoramos un hecho demasiado importante para conocer hacerca la herramienda Dante. The previous version of Dante relies a lot on DOM manipulation which causes a mix of presentation and logic. Even with their modular plugin system this condition suppose an sphagetti model to work with on every feature", "type": "blockquote", "depth": 0, "inlineStyleRanges": [{ "offset": 0, "length": 316, "style": "ITALIC" }], "entityRanges": [], "data": {} }, { "key": "2j6fk", "text": "Carlos Fred, 2020. Publicacion aquí.", "type": "blockquote", "depth": 0, "inlineStyleRanges": [{ "offset": 0, "length": 36, "style": "ITALIC" }, { "offset": 31, "length": 4, "style": "UNDERLINE" }], "entityRanges": [{ "offset": 31, "length": 4, "key": 1 }], "data": {} }, { "key": "1t4jk", "text": " ", "type": "unstyled", "depth": 0, "inlineStyleRanges": [], "entityRanges": [], "data": {} }], "entityMap": { "0": { "type": "LINK", "mutability": "MUTABLE", "data": { "href": "https://codesandbox.io/s/z2zxnl1x83?file=/src/index.js", "url": "https://codesandbox.io/s/z2zxnl1x83?file=/src/index.js" } }, "1": { "type": "LINK", "mutability": "MUTABLE", "data": { "href": "https://github.com/michelson/dante2", "url": "https://github.com/michelson/dante2" } } } }
  },
  {
    id: 2,
    slug: "la-casa-roja",
    title: "La casa roja de color verde",
    content: { "blocks": [{ "key": "6sv9n", "text": "La casa roja de color verde", "type": "header-one", "depth": 0, "inlineStyleRanges": [{ "offset": 0, "length": 22, "style": "BOLD" }], "entityRanges": [], "data": {} }, { "key": "q1nn", "text": "El dia de hoy se va celebrar una nueva version de la aplicacion de la Unidad Educativa Cardenal Gonzalez Zumarraga, este dia es un dia especial que todos compartimos y añoramos demasiado.Para conocer mas acerca de en que consiste esta celebracion dirigite a la siguiente publicacion, click aquí.Un dia como hoy 8 de Agosto del 2020, se conmemora la independencia de la unidad educativa Cardenal Gonzalez Zumarraga. Según cita el obispo Carlos Fred.", "type": "unstyled", "depth": 0, "inlineStyleRanges": [{ "offset": 290, "length": 4, "style": "UNDERLINE" }], "entityRanges": [{ "offset": 290, "length": 4, "key": 0 }], "data": {} }, { "key": "fsc9b", "text": "En este dia conmemoramos un hecho demasiado importante para conocer hacerca la herramienda Dante. The previous version of Dante relies a lot on DOM manipulation which causes a mix of presentation and logic. Even with their modular plugin system this condition suppose an sphagetti model to work with on every feature", "type": "blockquote", "depth": 0, "inlineStyleRanges": [{ "offset": 0, "length": 316, "style": "ITALIC" }], "entityRanges": [], "data": {} }, { "key": "2j6fk", "text": "Carlos Fred, 2020. Publicacion aquí.", "type": "blockquote", "depth": 0, "inlineStyleRanges": [{ "offset": 0, "length": 36, "style": "ITALIC" }, { "offset": 31, "length": 4, "style": "UNDERLINE" }], "entityRanges": [{ "offset": 31, "length": 4, "key": 1 }], "data": {} }, { "key": "1t4jk", "text": " ", "type": "unstyled", "depth": 0, "inlineStyleRanges": [], "entityRanges": [], "data": {} }], "entityMap": { "0": { "type": "LINK", "mutability": "MUTABLE", "data": { "href": "https://codesandbox.io/s/z2zxnl1x83?file=/src/index.js", "url": "https://codesandbox.io/s/z2zxnl1x83?file=/src/index.js" } }, "1": { "type": "LINK", "mutability": "MUTABLE", "data": { "href": "https://github.com/michelson/dante2", "url": "https://github.com/michelson/dante2" } } } }
  },
  {
    id: 3,
    slug: "la-casa-amarilla",
    title: "La casa amarilla de color verde",
    content: { "blocks": [{ "key": "6sv9n", "text": "La casa amarilla de color verde", "type": "header-one", "depth": 0, "inlineStyleRanges": [{ "offset": 0, "length": 22, "style": "BOLD" }], "entityRanges": [], "data": {} }, { "key": "q1nn", "text": "El dia de hoy se va celebrar una nueva version de la aplicacion de la Unidad Educativa Cardenal Gonzalez Zumarraga, este dia es un dia especial que todos compartimos y añoramos demasiado.Para conocer mas acerca de en que consiste esta celebracion dirigite a la siguiente publicacion, click aquí.Un dia como hoy 8 de Agosto del 2020, se conmemora la independencia de la unidad educativa Cardenal Gonzalez Zumarraga. Según cita el obispo Carlos Fred.", "type": "unstyled", "depth": 0, "inlineStyleRanges": [{ "offset": 290, "length": 4, "style": "UNDERLINE" }], "entityRanges": [{ "offset": 290, "length": 4, "key": 0 }], "data": {} }, { "key": "fsc9b", "text": "En este dia conmemoramos un hecho demasiado importante para conocer hacerca la herramienda Dante. The previous version of Dante relies a lot on DOM manipulation which causes a mix of presentation and logic. Even with their modular plugin system this condition suppose an sphagetti model to work with on every feature", "type": "blockquote", "depth": 0, "inlineStyleRanges": [{ "offset": 0, "length": 316, "style": "ITALIC" }], "entityRanges": [], "data": {} }, { "key": "2j6fk", "text": "Carlos Fred, 2020. Publicacion aquí.", "type": "blockquote", "depth": 0, "inlineStyleRanges": [{ "offset": 0, "length": 36, "style": "ITALIC" }, { "offset": 31, "length": 4, "style": "UNDERLINE" }], "entityRanges": [{ "offset": 31, "length": 4, "key": 1 }], "data": {} }, { "key": "1t4jk", "text": " ", "type": "unstyled", "depth": 0, "inlineStyleRanges": [], "entityRanges": [], "data": {} }], "entityMap": { "0": { "type": "LINK", "mutability": "MUTABLE", "data": { "href": "https://codesandbox.io/s/z2zxnl1x83?file=/src/index.js", "url": "https://codesandbox.io/s/z2zxnl1x83?file=/src/index.js" } }, "1": { "type": "LINK", "mutability": "MUTABLE", "data": { "href": "https://github.com/michelson/dante2", "url": "https://github.com/michelson/dante2" } } } }
  }
];

export default (_req: NextApiRequest, res: NextApiResponse) => {
  res.statusCode = 200;
  return res.json(posts);
}